### ISSUE TITLE
Repository description and README

### ISSUE THREAD

**Issue by zero323** [awesome-spark/spark-gotchas#14]
It would be nice to have some description and / or README (beyond TOC). Any ideas?

**Comment by eliasah** [comment]
I think that we have discussed that on slack once. What was the reason we intended to write gotchas in the first place ?

**Comment by eliasah** [comment]
Did you give this a thought ?

**Comment by zero323** [comment]
I added short description a while ago. Regarding readme no. Maybe when intro comes to life it can be included there.
