### ISSUE TITLE
Describe non-lazy evaluation in DataFrameReader

### ISSUE THREAD

**Issue by zero323** [awesome-spark/spark-gotchas#3]
WIP: https://github.com/awesome-spark/spark-gotchas/blob/04-non-lazy-evaluation/04_dataframe_by_example.md

**Comment by eliasah** [comment]
Maybe we need to say why we want to talk about this.

**Comment by zero323** [comment]
My motivation? So I don't have a reference material :)  But it can also have unexpected consequences. Don't think that the examples I provided are a good justification by itself?
