### ISSUE TITLE
Small deployments and spark.dynamicAllocation.maxExecutors

### ISSUE THREAD

**Issue by zero323** [awesome-spark/spark-gotchas#4]
I mean following issue in particular: https://awesome-spark.slack.com/archives/D0TAP9J1H/p1459408921000142

**Comment by eliasah** [comment]
What do you think about [this](http://stackoverflow.com/a/36475604/3415409) ?

**Comment by zero323** [comment]
Good starting point for sure.

**Comment by zero323** [comment]
Closed by #47
