### ISSUE TITLE
Need help related with Spark

### ISSUE THREAD

**Issue by akshaymhetre** [awesome-spark/spark-gotchas#57]
Hi,

I need your help on one of the questions on spark.  Sorry, I did not get any way to contact you apart from this. As you have already answered similar kind of question on stackoveflow, I thought you would be able to help me on this. Here is the link to my question : [question](https://stackoverflow.com/questions/44622638/need-a-specific-function-in-spark-which-will-check-whether-all-elements-matches) 
This is the usecase which I am trying to solve : [usecase](https://stackoverflow.com/questions/44589897/need-help-in-filtering-records-according-to-set-of-rules-with-apache-spark)

**Comment by eliasah** [comment]
I'm sorry @akshaymhetre . We don't deal with these types of requests on this repo first to start with. And if you need a consultant to hire, you can check our profile page on stackoverflow. Best of luck !
